#!/usr/bin/env bash

VERSION=0.1.0

sanity_check() {
    if ! command -v tmux &>/dev/null; then
        echo "==> tmux is not installed. Please install it first."
        exit 1
    fi

    if ! command -v fzf &>/dev/null; then
        echo "==> fzf is not installed. Please install it first."
        exit 1
    fi

    if ! command -v timeout &>/dev/null; then
        echo "==> timeout is not installed. If you're on macos install coreutils first."
        exit 1
    fi
}

write_config() {
    read -rp "==> Enter cluster URL: " url
    echo "==> Trying to authenticate via browser..."
    oc login -w --server "$url" --kubeconfig "$1" &> /dev/null
    echo "==> Cluster configuration created at $1"
}

is_tmux_running() {
    local tmux_running=$(pgrep tmux)

    if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
        return 1
    fi
    return 0
}

has_session() {
    tmux list-sessions | grep -q "^$1:"
}

switch_to() {
    if [[ -z $TMUX ]]; then
        tmux attach-session -t "$1"
    else
        tmux switch-client -t "$1"
    fi
}

create() {
    if [[ -f "$cfg" ]]; then
        read -n 1 -rp "==> Configuration for cluster '$name' already exists. Overwrite? [y/N] "
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]
        then
            write_config "$cfg"
        fi
    else
        write_config "$cfg"
    fi

}

info() {
    if ! [[ -f $cfg ]]; then
        echo "==> Environment '$name' does not exist"
        return
    fi
    echo ":: $name"
    local ctx=$(cat "$cfg" | grep -F "current-context" | cut -d ' ' -f2)
    local token_expires=$(cat "$cfg" | grep -F "ocenv-token-expires" | cut -d ' ' -f2)
    if [[ -z $token_expires ]]; then
        hours_left="-"
    else
        hours_left=$(expr $(expr "$token_expires" - $(date +%s)) / 3600)
    fi
    printf "==> %-20s %s\n" "Cluster:" $(echo "$ctx" | cut -d '/' -f2)
    printf "==> %-20s %s\n" "User:" $(echo "$ctx" | cut -d '/' -f3)
    printf "==> %-20s %s hours\n" "Session expires in:" $hours_left
    printf "==> %-20s %s\n" "Namespace:" $(echo "$ctx" | cut -d '/' -f1)
}

use() {
    if ! [[ -f $cfg ]]; then
        read -n 1 -rp "==> Configuration for cluster '$name' does not exist. Create? [y/N] "
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]
        then
            write_config "$cfg"
        else
            return
        fi
    fi

    local token_expires=$(cat "$cfg" | grep -F "ocenv-token-expires" | cut -d ' ' -f2)
    if [[ -z "$token_expires" ]]; then
        oc whoami --kubeconfig "$cfg" &> /dev/null
    else
        local hours_left=$(expr $(expr "$token_expires" - $(date +%s)) / 3600)
    fi

    if [[ $? != 0 || hours_left < 8 ]]; then
        echo "==> Session expired. Trying to authenticate via browser..."
        # a minute to login should be plenty
        timeout 60 oc login -w --kubeconfig "$cfg" &> /dev/null

        if [[ $? != 0 ]]; then
            echo "==> Timeout time reached. Exiting..."
            exit 1
        fi
        echo "ocenv-token-expires: $(expr $(date +%s) + 3600 \* 24)" >> "$cfg"
    fi

    if ! is_tmux_running || ! has_session "$name"; then
        # tagging session with __ocenv
        tmux new-session -ds "$name" -t "__ocenv" -c $PWD -e KUBECONFIG="$cfg"
    fi

    local current_session=$(tmux display-message -p '#S')
    if [[ "$current_session" != "$name" ]]; then
        switch_to "$name"
    else
        echo "==> Environment '$name' is already active"
    fi

}

remove() {
    # surely this is safe?
    if ! [[ -f $cfg ]]; then
        echo "==> Environment '$name' does not exist"
        return
    fi
    rm "$cfg"
        echo "==> Environment '$name' was removed"
}

list() {
    if [[ -n "$1" && "$1" == "--active" ]]; then
        if ! is_tmux_running; then
            echo "==> No running sessions found"
            return
        fi
        local sessions=$(get_sessions)

        if [[ -n "$sessions" ]]; then
            echo ":: Sessions"
            for s in "$sessions"; do
                echo "==> $s"
            done
        else
            echo "==> No running sessions found"
        fi
        return
    fi

    local envs=$(find ~/.kube/ocenv/ -name '*.yaml' -exec sh -c 'basename ${1%.*}' _ {} \;)
    if [[ -n "$envs" ]]; then
        echo ":: Environments"
        for e in "$envs"; do
            echo "==> $e"
        done
    else
        echo "==> No environments found"
    fi
}

get_sessions() {
    tmux list-sessions -F '#S #{session_group}' | grep '__ocenv' | cut -d ' ' -f1
}

# MAIN
sanity_check
subcommand=$1

if [[ -z "$subcommand" ]]; then
    if ! is_tmux_running; then
        echo "==> No running sessions found"
        exit 0
    fi
    current_session=$(tmux display-message -p '#S')
    selected=$(get_sessions | grep -xFv "$current_session" | fzf)
    switch_to "$selected"
    exit 0
fi

if [[ "$subcommand" != "help" && "$subcommand" != "list" && "$subcommand" != "version" ]]; then
    name="$2"
    [[ -z "$name" ]] && read -rp "==> Enter cluster name: " name
    cfg="$HOME/.kube/ocenv/$name.yaml"
fi

case "$subcommand" in
    "create")
        create
        ;;
    "info")
        info
        ;;
    "rm")
        remove
        ;;
    "use")
        use
        ;;
    "list")
        list "$2"
        ;;
    "version")
        echo "ocenv v$VERSION"
        ;;
    *)
        printf "Usage: ocenv [SUBCOMMAND]\n"
        printf "Subcommands:\n"
        printf "  %-14s  %s\n" "create <NAME>" "Creates a new environment for a cluster"
        printf "  %-14s  %s\n" "list" "Lists all running sessions for configured environments"
        printf "  %-14s  %s\n" "rm <NAME>" "Removes environment"
        printf "  %-14s  %s\n" "use <NAME>" "Initializes a TMUX session with selected environment"
        printf "  %-14s  %s\n" "version" "Prints version information"
        printf "  %-14s  %s\n" "help" "Prints this help message"
        ;;
esac
