#!/usr/bin/env bash

create() {
    check_name $1
    if [[ -f "$cfg" ]]; then
        read -n 1 -rp "==> Configuration for cluster '$name' already exists. Overwrite? [y/N] "
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]
        then
            write_config "$cfg"
        fi
    else
        write_config "$cfg"
    fi

}

info() {
    local envs=()
    if [[ -n "$1" ]]; then
        check_name $1
        if ! [[ -f $cfg ]]; then
            echo "==> Environment '$name' does not exist"
            return
        fi
        envs+=($cfg)
    else
        local saved_envs=$(find ~/.kube/ocenv/ -name '*.yaml' -exec sh -c 'basename ${1%.*}' _ {} \;)
        # saved_envs=$(list | cut -d ' ' -f2)
        for e in $saved_envs; do
            envs+=("$HOME/.kube/ocenv/$e.yaml")
        done
    fi

    for e in $envs; do
        local n=$(basename ${e%.*})
        echo ":: $n"
        local ctx=$(yq '.current-context' $e)
        local token_expires=$(yq '.ocenv-token-expires' $e)
        if [[ -z $token_expires ]]; then
            hours_left="-"
        else
            hours_left=$(expr $(expr "$token_expires" - $(date +%s)) / 3600)
            if [[ $hours_left -lt 0 ]]; then
                hours_left="-"
            else
                hours_left="$hours_left hours"
            fi
        fi

        printf "==> %-20s %s\n" "Cluster:" $(echo "$ctx" | cut -d '/' -f2)
        printf "==> %-20s %s\n" "User:" $(echo "$ctx" | cut -d '/' -f3)
        printf "==> %-20s %s\n" "Session expires in:" $hours_left
        printf "==> %-20s %s\n" "Namespace:" $(echo "$ctx" | cut -d '/' -f1)
    done
}

_list_helper() {
    local entries=$1
    for e in $entries; do
        echo "$e"
    done
}

_list_active() {
    if ! is_tmux_running; then
        echo "==> No active sessions found"
        return
    fi
    local sessions=$(get_sessions)

    if [[ -n "$sessions" ]]; then
        echo ":: Sessions"
        _list_helper "$sessions"
    else
        echo "==> No active sessions found"
    fi
}

_list_all() {
    local envs=$(find ~/.kube/ocenv/ -name '*.yaml' -exec sh -c 'basename ${1%.*}' _ {} \;)
    if [[ -n "$envs" ]]; then
        echo ":: Environments"
        _list_helper "$envs"
    else
        echo "==> No environments found"
    fi
}

_list_help() {
    printf "Usage: ocenv list [OPTIONS]\n"
    printf "Options:\n"
    printf "  %-14s  %s\n" "-a, --active" "Lists all active sessions"
    printf "  %-14s  %s\n" "-h, --help" "Prints this help message"
}

list() {
    local active=0

    local list_opts=()
    while (( $# )); do
        case "$1" in
            --help) list_opts+=("-h"); shift ;;
            --active) list_opts+=("-a"); shift ;;
            --) list_opts+=("--"); shift; list_opts+=("$@"); set -- ;;
            *) list_opts+=("$1"); shift ;;
        esac
    done
    set -- "${list_opts[@]}"

    while getopts ":ah" opt; do
        case $opt in
            a) active=1 ;;
            h) _list_help; return ;;
            \?)
                _list_help
                echo "Invalid option: -$OPTARG" >&2
                return 1
                ;;
        esac
    done
    shift $((OPTIND -1))

    if [ $active -eq 1 ]; then
        _list_active
    else
        _list_all
    fi
}

remove() {
    # surely this is safe?
    check_name "$1"
    if ! [[ -f $cfg ]]; then
        echo "==> Environment '$name' does not exist"
        return
    fi
    rm "$cfg"
    echo "==> Environment '$name' was removed"
}

use() {
    check_name "$1"
    if ! [[ -f $cfg ]]; then
        read -n 1 -rp "==> Configuration for cluster '$name' does not exist. Create? [y/N] "
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]
        then
            write_config "$cfg"
        else
            return
        fi
    fi

    local token_expires=$(yq '.ocenv-token-expires' $cfg)
    if [[ -z "$token_expires" ]]; then
        oc whoami --kubeconfig "$cfg" &> /dev/null
        rc=$?
    else
        # local hours_left=$(($(("$token_expires" - $(date +%s))) / 3600))
        local hours_left=$(expr $(expr "$token_expires" - $(date +%s)) / 3600)
    fi

    if [[ $rc -ne 0 || $hours_left -lt 8 ]]; then
        echo "==> Session expired. Trying to authenticate via browser..."
        # a minute to login should be plenty
        timeout 60 oc login -w --kubeconfig "$cfg" &> /dev/null

        if [[ $? -ne 0 ]]; then
            echo "==> Timeout time reached. Exiting..."
            exit 1
        fi
        yq -i ".ocenv-token-expires = $(expr $(date +%s) + 3600 \* 24)" "$cfg"
        # yq -i ".ocenv-token-expires = $(($(date +%s) + 3600 \* 24))" "$cfg"
    fi

    local current_session=$(tmux display-message -p '#S')
    if ! is_tmux_running || ! has_session "$name"; then
        tmux new-session -ds "_ocenv_$name" -c $PWD -e KUBECONFIG="$cfg"
        # should work
        current_session=""
    fi

    if [[ "$current_session" != "$name" ]]; then
        switch_to "$name"
    else
        echo "==> Environment '$name' is already active"
    fi

}


